SchwarzIT/go-template

- .github/workflows/semgrep.yml
Upload semgrep output to github security dashboard.
Fixes #25
> Enable security dashboard for semgrep

- .github/renovate.json
fixes #30 
Signed-off-by: Engin Diri <engin.diri@mail.schwarz>
The dashboard is not useful, on most project have it disabled.
> fix: remove Dependency Dashboard

- README.md
Add a new badge from goreportcard.com
[![Go Report Card](https://goreportcard.com/badge/github.com/SchwarzIT/go-template)](https://goreportcard.com/report/github.com/SchwarzIT/go-template)
Signed-off-by: Steffen Exler <Steffen.Exler@mail.schwarz>
> docs: add go report card badge

- _template/README.md
Remove space after badge in readme.
Signed-off-by: Steffen Exler <Steffen.Exler@mail.schwarz>
> docs: remove space after badge

- pkg/gotemplate/options.go
Working with the template, I encountered the following:
linting the repository that just was created, the linter errors due to not handling the error from the logger.Sync() call.
```bash
Error return value of `logger.Sync` is not checked (errcheck)
defer logger.Sync()
^
```
In addition I think it is more convenient to start with a `cmd/{{.projectName}}` instead of `cmd/awesomecli` if nothing else is specified.
> feat(template): use projectSlug as default for appName

- pkg/gotemplate/options.go
- pkg/gotemplate/testdata/values.yml
Set no open source license value to 0 instead of 9.
> refactor(template)!: set no open source license value to 0

- _template/.azure-pipelines.yml
- _template/.github/workflows/main.yml
- _template/.github/workflows/semgrep.yml
- _template/.gitlab-ci.yml
- cmd/dotembed/main_test.go
- embed_gen.go
- pkg/gotemplate/options.go
- pkg/gotemplate/testdata/values.yml
Add options to enable a CI for the following provider
- GitHub
- GitLab
- Azure DevOps
> feat(template): add ci options

- .github/renovate.json
Now that we also use renovate for the actions which are updated regularly we should use this to not flood the repo with PRs.
> feat(deps): group all non major renovate PRs

- .github/workflows/main.yml
- .github/workflows/release.yaml
- .github/workflows/semgrep.yml
Signed-off-by: Tobias Brumhard <tobias.brumhard@mail.schwarz>
> feat(ci): pin all github action versions

- .github/workflows/semgrep.yml
The CI currently fails in the semgrep step. Could have sth to do with the SARIF report being generated since that is the step after which the error is reported.
Example fail: https://github.com/SchwarzIT/go-template/runs/5693803886
Issue: https://github.com/returntocorp/semgrep-action/issues/548
> fix(ci): disable semgrep sarif report

- .github/workflows/main.yml
- .github/workflows/release.yaml
- Makefile
- _template/.azure-pipelines.yml
- _template/.github/workflows/main.yml
- go.mod
- pkg/gocli/version_test.go
Signed-off-by: Tobias Brumhard <tobias.brumhard@mail.schwarz>
> chore(engine): update to go1.18

- _template/Dockerfile
Pin docker images by default, so that semgrep will run without problems.
> feat(template): Pin docker images

- _template/cmd/{{.Base.appName}}/main.go
- _template/internal/logger/logger.go
Set zap log level via environment var `LOG_LEVEL`. If `LOG_LEVEL` is `debug`, zap will be set to development and per default zap is set to production.
Signed-off-by: Steffen Exler <Steffen.Exler@mail.schwarz>
> feat(template): Set ZAP loglevel via environment var

- pkg/gotemplate/new.go
Set new generated files to 0644 and directory to 0755 permission.
Fixes #105
> feat(template): Set directory & file permission

- .github/workflows/release.yaml
Should fix release pipeline fails like https://github.com/SchwarzIT/go-template/actions/runs/2256549308
Also this seams to be the default according to docs:
https://goreleaser.com/ci/actions/
> fix(ci): set correct release pipeline permissions

- .github/workflows/release.yaml
Since #111 didn't work, I forked the repo and checked the permissions again. Turns out I added the `contents: write` permissions globally which was then overwritten by the release steps `permissions`.
This now works on the fork, so this should fix the pipeline.
> fix(ci): add content write permissions for release

- _template/Makefile
> fix(template): change branch name in protobreaking from master to main (#125)

- Makefile
- README.md
- flake.lock
- flake.nix
- nix/gomod2nix.toml
This PR adds a flake.nix file which is used to install go-template within the nix ecosystem.
In the future this could also be used to provide dev environments for developers.
> feat: add flake.nix file to consume gt via nix

- .github/workflows/release.yaml
Temporarily treats #179 until https://github.com/goreleaser/goreleaser/issues/3573 is fixed.
That enables the creation of new releases until the bug fix.
The used version is the last working version from https://github.com/SchwarzIT/go-template/actions/runs/2924879055
> fix(ci): pin goreleaser version to v1.10.3

- .github/workflows/tag_release.yaml
Fixes #178 
Turns out that actions won't trigger other actions unless a PAT is used (see https://github.com/orgs/community/discussions/25702).
Therefore, it will be necessary that @patrick246 creates a PAT secret for that repo that the workflow can use.
> fix(ci): git push new tag in tag_release

- flake.lock
- nix/gomod2nix.toml
This PR updates the flake dependencies and regenerates the `gomod2nix.toml` since I forgot to do so in the last PRs (forgot to init the githooks on the new PC).
Shows that we should probably fix https://github.com/SchwarzIT/go-template/issues/40 sometime soon.
> fix: update and fix nix flake

- .github/workflows/main.yml
Set a fix version of Go in the workflow and get rid of the Go version matrix.
>  fix(ci): Set fix Go version in main Workflow

- pkg/gotemplate/options.go
Remove Codeowners when no OpenSource license is selected.
Fix: #152
> fix(engine): Remove Codeowners when no OpenSource project

- _template/Dockerfile
- _template/Makefile
Update Dockerfile version and enable `link` flag while for `COPY` within Dockerfile.
Fix: https://github.com/SchwarzIT/go-template/issues/100
> feat(template): Add more caching to docker build

- CODEOWNERS
The emails we used in the codeowners are outdated so I thought it would be better to use the github handles since I guess they won't change as much.
> feat: update codeowners to use github handles

- .github/workflows/main.yml
E.g. in this CI run https://github.com/SchwarzIT/go-template/actions/runs/4704835624/jobs/8344803718 I saw that push was skipped because the condition for the push was not correct.
This should fix that.
> fix(ci): trigger push on generated files

- .github/workflows/main.yml
- .golangci.yml
- _template/.golangci.yml
- nix/gomod2nix.toml
The new standard config for the depguard linter since golangci-lint 1.53 allows only the standard library in all files. As depguard is not further configured, we can just remove it and get the old behavior back
> fix(template): remove depguard linter

- .github/workflows/main.yml
- Makefile
Currently, all the pipelines fail due to a vulnerability detected by govulncheck which is only fixed in go1.21 which is not yet released.
There's no way to ignore vulns in govulncheck sadly.
Since this is a CLI and also we're using all the latest versions from renovatebot, the report doesn't really have much value since there's nothign we can really do about it
> fix(ci): remove govulncheck from main pipeline
